# Assignment: Compresive Strength Concrete Problem


### Abstract: 

Concrete is the most important material in civil engineering. The concrete compressive strength (concrete strength to bear the load) is a highly nonlinear function of age and ingredients.  <br><br>

<table border="1"  cellpadding="6" bordercolor="red">
	<tbody>
        <tr>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Data Set Characteristics:&nbsp;&nbsp;</b></p></td>
		<td><p class="normal">Multivariate</p></td>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Number of Instances:</b></p></td>
		<td><p class="normal">1030</p></td>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Area:</b></p></td>
		<td><p class="normal">Physical</p></td>
        </tr>
     </tbody>
    </table>
<table border="1" cellpadding="6">
    <tbody>
        <tr>
            <td bgcolor="#DDEEFF"><p class="normal"><b>Attribute Characteristics:</b></p></td>
            <td><p class="normal">Real</p></td>
            <td bgcolor="#DDEEFF"><p class="normal"><b>Number of Attributes:</b></p></td>
            <td><p class="normal">9</p></td>
            <td bgcolor="#DDEEFF"><p class="normal"><b>Date Donated</b></p></td>
            <td><p class="normal">2007-08-03</p></td>
        </tr>
     </tbody>
    </table>
<table border="1" cellpadding="6">	
    <tbody>
    <tr>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Associated Tasks:</b></p></td>
		<td><p class="normal">Regression</p></td>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Missing Values?</b></p></td>
		<td><p class="normal">N/A</p></td>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Number of Web Hits:</b></p></td>
		<td><p class="normal">231464</p></td>
	</tr>
    </tbody>
    </table>

###  Description:
| Features Name | Data Type | Measurement | Description |
| -- | -- | -- | -- |
Cement (component 1) | quantitative | kg in a m3 mixture | Input Variable
Blast Furnace Slag (component 2) | quantitative | kg in a m3 mixture | Input Variable
Fly Ash (component 3) | quantitative | kg in a m3 mixture | Input Variable
Water (component 4) | quantitative | kg in a m3 mixture | Input Variable
Superplasticizer (component 5) | quantitative | kg in a m3 mixture | Input Variable
Coarse Aggregate (component 6) | quantitative | kg in a m3 mixture | Input Variable
Fine Aggregate (component 7) | quantitative | kg in a m3 mixture | Input Variable
Age | quantitative | Day (1~365) | Input Variable
Concrete compressive strength | quantitative | MPa | Output Variable

### WORKFLOW :
- Load Data
- Check Missing Values ( If Exist ; Fill each record with mean of its feature )
- Standardized the Input Variables. **Hint**: Centeralized the data
- Split into 50% Training(Samples,Labels) , 30% Test(Samples,Labels) and 20% Validation Data(Samples,Labels).
- Model : input Layer (No. of features ), 3 hidden layers including 10,8,6 unit & Output Layer with activation function relu/tanh (check by experiment).
- Compilation Step (Note : Its a Regression problem , select loss , metrics according to it)
- Train the Model with Epochs (100) and validate it
- If the model gets overfit tune your model by changing the units , No. of layers , activation function , epochs , add dropout layer or add Regularizer according to the need .
- Evaluation Step
- Prediction

# Load Data:
[Click Here to Download DataSet](https://github.com/ramsha275/ML_Datasets/blob/main/compresive_strength_concrete.csv)

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [6]:
df = pd.read_csv("/content/compresive_strength_concrete.csv")
df.head()

   Cement (component 1)(kg in a m^3 mixture)  ...  Concrete compressive strength(MPa, megapascals)
0                                      540.0  ...                                             79.99
1                                      540.0  ...                                             61.89
2                                      332.5  ...                                             40.27
3                                      332.5  ...                                             41.05
4                                      198.6  ...                                             44.30

[5 rows x 9 columns]

In [7]:
df.fillna(df.mean())

      Cement (component 1)(kg in a m^3 mixture)  ...  Concrete compressive strength(MPa, megapascals)
0                                         540.0  ...                                             79.99
1                                         540.0  ...                                             61.89
2                                         332.5  ...                                             40.27
3                                         332.5  ...                                             41.05
4                                         198.6  ...                                             44.30
...                                         ...  ...                                               ...
1025                                      276.4  ...                                             44.28
1026                                      322.2  ...                                             31.18
1027                                      148.5  ...                                             23.70
1028                                      159.1  ...                                             32.77
1029                                      260.9  ...                                             32.40

[1030 rows x 9 columns]

In [8]:
df.columns = ["cement", "bfs", "fly_ash", "water", "superplasticizer", "coarse_aggregate", "fine_aggregate", "age", "ccs"]
df

      cement    bfs  fly_ash  ...  fine_aggregate  age    ccs
0      540.0    0.0      0.0  ...           676.0   28  79.99
1      540.0    0.0      0.0  ...           676.0   28  61.89
2      332.5  142.5      0.0  ...           594.0  270  40.27
3      332.5  142.5      0.0  ...           594.0  365  41.05
4      198.6  132.4      0.0  ...           825.5  360  44.30
...      ...    ...      ...  ...             ...  ...    ...
1025   276.4  116.0     90.3  ...           768.3   28  44.28
1026   322.2    0.0    115.6  ...           813.4   28  31.18
1027   148.5  139.4    108.6  ...           780.0   28  23.70
1028   159.1  186.7      0.0  ...           788.9   28  32.77
1029   260.9  100.5     78.3  ...           761.5   28  32.40

[1030 rows x 9 columns]

In [10]:
y = df['ccs']
df.drop('ccs', axis =1, inplace = True)
x = df.copy()

In [12]:
y.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: ccs, dtype: float64

In [13]:
x.head()

   cement    bfs  fly_ash  ...  coarse_aggregate  fine_aggregate  age
0   540.0    0.0      0.0  ...            1040.0           676.0   28
1   540.0    0.0      0.0  ...            1055.0           676.0   28
2   332.5  142.5      0.0  ...             932.0           594.0  270
3   332.5  142.5      0.0  ...             932.0           594.0  365
4   198.6  132.4      0.0  ...             978.4           825.5  360

[5 rows x 8 columns]

In [20]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3)

In [22]:
print(df.shape)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(1030, 8)
(721, 8)
(721,)
(309, 8)
(309,)

In [23]:
x_train, x_val, y_train, y_val = train_test_split(x_train,y_train, test_size=0.2)

In [24]:
print(df.shape)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)
print(x_val.shape)
print(y_val.shape)

(1030, 8)
(576, 8)
(576,)
(309, 8)
(309,)
(145, 8)
(145,)

In [26]:
model = Sequential()
model.add(Dense(10, activation='relu', input_shape=(x_train.shape)))
model.add(Dense(8, activation='relu'))
model.add(Dense(6, activation='relu'))
model.add(Dense(1))

In [27]:
model.compile('Adam', loss='mse', metrics='mae')

In [28]:
model.fit(x_train, y_train, epochs=100, verbose=1)

Epoch 1/100
WARNING:tensorflow:Model was constructed with shape (None, 576, 8) for input KerasTensor(type_spec=TensorSpec(shape=(None, 576, 8), dtype=tf.float32, name='dense_1_input'), name='dense_1_input', description="created by layer 'dense_1_input'"), but it was called on an input with incompatible shape (32, 8).
WARNING:tensorflow:Model was constructed with shape (None, 576, 8) for input KerasTensor(type_spec=TensorSpec(shape=(None, 576, 8), dtype=tf.float32, name='dense_1_input'), name='dense_1_input', description="created by layer 'dense_1_input'"), but it was called on an input with incompatible shape (32, 8).
18/18 [==============================] - 1s 1ms/step - loss: 33984.2283 - mae: 178.9440
Epoch 2/100
18/18 [==============================] - 0s 1ms/step - loss: 6231.4595 - mae: 71.9071
Epoch 3/100
18/18 [==============================] - 0s 1ms/step - loss: 1065.3697 - mae: 27.0383
Epoch 4/100
18/18 [==============================] - 0s 1ms/step - loss: 524.5926 - mae: 17.7443
Epoch 5/100
18/18 [==============================] - 0s 1ms/step - loss: 449.3225 - mae: 16.8183
Epoch 6/100
18/18 [==============================] - 0s 1ms/step - loss: 360.0746 - mae: 15.3422
Epoch 7/100
18/18 [==============================] - 0s 1ms/step - loss: 335.4804 - mae: 14.6363
Epoch 8/100
18/18 [==============================] - 0s 1ms/step - loss: 290.5548 - mae: 13.7017
Epoch 9/100
18/18 [==============================] - 0s 1ms/step - loss: 316.6875 - mae: 14.1259
Epoch 10/100
18/18 [==============================] - 0s 1ms/step - loss: 286.0775 - mae: 13.5442
Epoch 11/100
18/18 [==============================] - 0s 2ms/step - loss: 296.3407 - mae: 13.7252
Epoch 12/100
18/18 [==============================] - 0s 1ms/step - loss: 310.9330 - mae: 14.0088
Epoch 13/100
18/18 [==============================] - 0s 2ms/step - loss: 284.5878 - mae: 13.3897
Epoch 14/100
18/18 [==============================] - 0s 1ms/step - loss: 258.1027 - mae: 12.7861
Epoch 15/100
18/18 [==============================] - 0s 1ms/step - loss: 254.9134 - mae: 12.7191
Epoch 16/100
18/18 [==============================] - 0s 1ms/step - loss: 245.3399 - mae: 12.3439
Epoch 17/100
18/18 [==============================] - 0s 1ms/step - loss: 241.3636 - mae: 12.4525
Epoch 18/100
18/18 [==============================] - 0s 1ms/step - loss: 219.0148 - mae: 11.8569
Epoch 19/100
18/18 [==============================] - 0s 1ms/step - loss: 228.5082 - mae: 12.1328
Epoch 20/100
18/18 [==============================] - 0s 1ms/step - loss: 226.7515 - mae: 12.0273
Epoch 21/100
18/18 [==============================] - 0s 1ms/step - loss: 217.8629 - mae: 11.6787
Epoch 22/100
18/18 [==============================] - 0s 1ms/step - loss: 201.9547 - mae: 11.1499
Epoch 23/100
18/18 [==============================] - 0s 1ms/step - loss: 209.0832 - mae: 11.3750
Epoch 24/100
18/18 [==============================] - 0s 1ms/step - loss: 198.5765 - mae: 11.1229
Epoch 25/100
18/18 [==============================] - 0s 1ms/step - loss: 188.1653 - mae: 10.8512
Epoch 26/100
18/18 [==============================] - 0s 1ms/step - loss: 198.8154 - mae: 11.0874
Epoch 27/100
18/18 [==============================] - 0s 1ms/step - loss: 187.6592 - mae: 10.6482
Epoch 28/100
18/18 [==============================] - 0s 1ms/step - loss: 203.7342 - mae: 11.2736
Epoch 29/100
18/18 [==============================] - 0s 2ms/step - loss: 190.9936 - mae: 10.8760
Epoch 30/100
18/18 [==============================] - 0s 2ms/step - loss: 186.7944 - mae: 10.7947
Epoch 31/100
18/18 [==============================] - 0s 1ms/step - loss: 191.0589 - mae: 10.7391
Epoch 32/100
18/18 [==============================] - 0s 2ms/step - loss: 164.2357 - mae: 10.0679
Epoch 33/100
18/18 [==============================] - 0s 1ms/step - loss: 164.8937 - mae: 9.9511
Epoch 34/100
18/18 [==============================] - 0s 1ms/step - loss: 162.1709 - mae: 10.0572
Epoch 35/100
18/18 [==============================] - 0s 1ms/step - loss: 146.2616 - mae: 9.3872
Epoch 36/100
18/18 [==============================] - 0s 1ms/step - loss: 173.6555 - mae: 10.2207
Epoch 37/100
18/18 [==============================] - 0s 1ms/step - loss: 165.3313 - mae: 10.2497
Epoch 38/100
18/18 [==============================] - 0s 1ms/step - loss: 165.2620 - mae: 9.9508
Epoch 39/100
18/18 [==============================] - 0s 1ms/step - loss: 147.3495 - mae: 9.4177
Epoch 40/100
18/18 [==============================] - 0s 1ms/step - loss: 172.5285 - mae: 10.3307
Epoch 41/100
18/18 [==============================] - 0s 1ms/step - loss: 151.6410 - mae: 9.5373
Epoch 42/100
18/18 [==============================] - 0s 1ms/step - loss: 135.5177 - mae: 9.1562
Epoch 43/100
18/18 [==============================] - 0s 1ms/step - loss: 140.0091 - mae: 9.2413
Epoch 44/100
18/18 [==============================] - 0s 1ms/step - loss: 138.3773 - mae: 9.2307
Epoch 45/100
18/18 [==============================] - 0s 1ms/step - loss: 155.3341 - mae: 9.7387
Epoch 46/100
18/18 [==============================] - 0s 1ms/step - loss: 144.8607 - mae: 9.6457
Epoch 47/100
18/18 [==============================] - 0s 1ms/step - loss: 133.3782 - mae: 9.2331
Epoch 48/100
18/18 [==============================] - 0s 2ms/step - loss: 130.7234 - mae: 8.8402
Epoch 49/100
18/18 [==============================] - 0s 1ms/step - loss: 132.1114 - mae: 9.0416
Epoch 50/100
18/18 [==============================] - 0s 1ms/step - loss: 134.7303 - mae: 9.1028
Epoch 51/100
18/18 [==============================] - 0s 1ms/step - loss: 141.6217 - mae: 9.3086
Epoch 52/100
18/18 [==============================] - 0s 2ms/step - loss: 143.9477 - mae: 9.3965
Epoch 53/100
18/18 [==============================] - 0s 1ms/step - loss: 127.7430 - mae: 8.8502
Epoch 54/100
18/18 [==============================] - 0s 2ms/step - loss: 139.4234 - mae: 9.3056
Epoch 55/100
18/18 [==============================] - 0s 2ms/step - loss: 141.6726 - mae: 9.2846
Epoch 56/100
18/18 [==============================] - 0s 1ms/step - loss: 131.5227 - mae: 9.0414
Epoch 57/100
18/18 [==============================] - 0s 1ms/step - loss: 126.7735 - mae: 8.8531
Epoch 58/100
18/18 [==============================] - 0s 1ms/step - loss: 127.5721 - mae: 8.8528
Epoch 59/100
18/18 [==============================] - 0s 1ms/step - loss: 126.3398 - mae: 8.9944
Epoch 60/100
18/18 [==============================] - 0s 2ms/step - loss: 124.1706 - mae: 8.7840
Epoch 61/100
18/18 [==============================] - 0s 1ms/step - loss: 135.2232 - mae: 9.1802
Epoch 62/100
18/18 [==============================] - 0s 2ms/step - loss: 144.1215 - mae: 9.3135
Epoch 63/100
18/18 [==============================] - 0s 2ms/step - loss: 124.4670 - mae: 8.9444
Epoch 64/100
18/18 [==============================] - 0s 1ms/step - loss: 122.7950 - mae: 8.8045
Epoch 65/100
18/18 [==============================] - 0s 2ms/step - loss: 124.4078 - mae: 8.7617
Epoch 66/100
18/18 [==============================] - 0s 1ms/step - loss: 128.6199 - mae: 8.7595
Epoch 67/100
18/18 [==============================] - 0s 1ms/step - loss: 119.5276 - mae: 8.6403
Epoch 68/100
18/18 [==============================] - 0s 1ms/step - loss: 114.9218 - mae: 8.4003
Epoch 69/100
18/18 [==============================] - 0s 2ms/step - loss: 122.7657 - mae: 8.9364
Epoch 70/100
18/18 [==============================] - 0s 2ms/step - loss: 119.5446 - mae: 8.6495
Epoch 71/100
18/18 [==============================] - 0s 2ms/step - loss: 129.5299 - mae: 9.1006
Epoch 72/100
18/18 [==============================] - 0s 1ms/step - loss: 122.1194 - mae: 8.7557
Epoch 73/100
18/18 [==============================] - 0s 2ms/step - loss: 121.4496 - mae: 8.8750
Epoch 74/100
18/18 [==============================] - 0s 1ms/step - loss: 116.8591 - mae: 8.5031
Epoch 75/100
18/18 [==============================] - 0s 1ms/step - loss: 116.5208 - mae: 8.4512
Epoch 76/100
18/18 [==============================] - 0s 1ms/step - loss: 114.5982 - mae: 8.4092
Epoch 77/100
18/18 [==============================] - 0s 2ms/step - loss: 110.8844 - mae: 8.3360
Epoch 78/100
18/18 [==============================] - 0s 2ms/step - loss: 110.2122 - mae: 8.3234
Epoch 79/100
18/18 [==============================] - 0s 1ms/step - loss: 118.8361 - mae: 8.7045
Epoch 80/100
18/18 [==============================] - 0s 2ms/step - loss: 116.1117 - mae: 8.5746
Epoch 81/100
18/18 [==============================] - 0s 2ms/step - loss: 100.5220 - mae: 7.8998
Epoch 82/100
18/18 [==============================] - 0s 2ms/step - loss: 126.4318 - mae: 8.8373
Epoch 83/100
18/18 [==============================] - 0s 2ms/step - loss: 116.8284 - mae: 8.5842
Epoch 84/100
18/18 [==============================] - 0s 1ms/step - loss: 111.9686 - mae: 8.4164
Epoch 85/100
18/18 [==============================] - 0s 1ms/step - loss: 120.7505 - mae: 8.7067
Epoch 86/100
18/18 [==============================] - 0s 1ms/step - loss: 109.5565 - mae: 8.2499
Epoch 87/100
18/18 [==============================] - 0s 1ms/step - loss: 122.4731 - mae: 8.7555
Epoch 88/100
18/18 [==============================] - 0s 1ms/step - loss: 114.7267 - mae: 8.5232
Epoch 89/100
18/18 [==============================] - 0s 2ms/step - loss: 117.8530 - mae: 8.7163
Epoch 90/100
18/18 [==============================] - 0s 1ms/step - loss: 125.3077 - mae: 8.8331
Epoch 91/100
18/18 [==============================] - 0s 2ms/step - loss: 103.7751 - mae: 8.2214
Epoch 92/100
18/18 [==============================] - 0s 1ms/step - loss: 119.5503 - mae: 8.7045
Epoch 93/100
18/18 [==============================] - 0s 2ms/step - loss: 113.8240 - mae: 8.5003
Epoch 94/100
18/18 [==============================] - 0s 1ms/step - loss: 109.6695 - mae: 8.2503
Epoch 95/100
18/18 [==============================] - 0s 1ms/step - loss: 116.1219 - mae: 8.4254
Epoch 96/100
18/18 [==============================] - 0s 1ms/step - loss: 107.0176 - mae: 8.2319
Epoch 97/100
18/18 [==============================] - 0s 2ms/step - loss: 111.2066 - mae: 8.2531
Epoch 98/100
18/18 [==============================] - 0s 2ms/step - loss: 108.4394 - mae: 8.3086
Epoch 99/100
18/18 [==============================] - 0s 1ms/step - loss: 121.8087 - mae: 8.6919
Epoch 100/100
18/18 [==============================] - 0s 1ms/step - loss: 120.9816 - mae: 8.7431

**Testing**

In [29]:
print(x_test.shape, np.asarray(y_test.shape) )

(309, 8) [309]

In [30]:
index = 10
# X_test.head()
ans = model.predict( x_test[index-1:index] )
print( ans, np.asarray(y_test[index-1:index]) )

WARNING:tensorflow:Model was constructed with shape (None, 576, 8) for input KerasTensor(type_spec=TensorSpec(shape=(None, 576, 8), dtype=tf.float32, name='dense_1_input'), name='dense_1_input', description="created by layer 'dense_1_input'"), but it was called on an input with incompatible shape (None, 8).
[[56.65378]] [37.92]